# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
dropcolor = 0xb7c4ff80
splitcolor = 0xe4bad9ff
focuscolor = 0xb7c4ffff
maximizescreencolor = 0xc2c5ddff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe4bad9ff
globalcolor = 0x2b4090ff
overlaycolor = 0x424659ff
jump_label_decorate_fg_color = 0xe2e2e2ff
jump_label_decorate_bg_color = 0x2a2a2aff
jump_label_decorate_focus_fg_color = 0x0e2878ff
jump_label_decorate_focus_bg_color = 0xb7c4ffff
jump_label_decorate_border_color = 0x919191ff
group_bar_decorate_fg_color = 0xe2e2e2ff
group_bar_decorate_bg_color = 0x2a2a2aff
group_bar_decorate_focus_fg_color = 0x0e2878ff
group_bar_decorate_focus_bg_color = 0xb7c4ffff
group_bar_decorate_border_color = 0x919191ff
